default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: sunil123
  host: localhost

development:
  <<: *default
  database: rj_project

test:
  <<: *default
  database: rj_project

production:
  <<: *default
  database: rj_project
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
